trigger:
  - dev  # Runs on commits to 'dev' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageName: 'halayahia22/springboot-app'

stages:
  - stage: Lint
    jobs:
      - job: LintCode
        steps:
          - script: ./gradlew check
            displayName: 'Run Linting'

  - stage: Unit_Test
    dependsOn: Lint
    jobs:
      - job: RunTests
        steps:
          - script: ./gradlew test
            displayName: 'Run Unit Tests'

  - stage: Build_Image
    dependsOn: Unit_Test
    jobs:
      - job: BuildDockerImage
        steps:
          - script: docker build -t $(imageName):$(Build.BuildId) .
            displayName: 'Build Docker Image'

  - stage: Push_Image
    dependsOn: Build_Image
    jobs:
      - job: PushToRegistry
        steps:
          - script: |
              docker tag $(imageName):$(Build.BuildId) $(imageName):latest
              echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
              docker push $(imageName):$(Build.BuildId)
              docker push $(imageName):latest
            displayName: 'Push Docker Image to Registry'