apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: halayahia22/junior-devops-engineer-test:latest  # ✅ Corrected image name
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
